### ISSUE TITLE
The ghost entry can crash the game upon touching

### ISSUE THREAD

**Issue by Rob23oba** [L4Vo5/i-wanna-lockpick-editor#1]
When the player touches the ghost entry, the game crashes.

**How to reproduce:**
1. Place the player on the top left corner of the editor area.
2. Press "Play".
3. The editor crashes.

**Explanation:**
In the top left corner of the editor area is the ghost entry which has no entry data (`entry_data == null`). This entry will however trigger the `_on_area_detect_area_entered` function of kid.gd which causes `player_touching` to run on the ghost entry. `player_touching` however expects the entry to have entry data which causes the editor to crash.

**Fix:**
Add a check in entry.gd that the entry is not the ghost entry:
```gdscript
# called by kid.gd
func player_touching() -> void:
	if entry_data == null:
		# ghost entry
		return
	if entry_data.leads_to >= 0 and entry_data.leads_to < pack_data.levels.size():
		arrow.show()
```

**Comment by L4Vo5** [comment]
Fixed after your PR
